### ISSUE TITLE
JOSS Review - Final remarks

### ISSUE THREAD

**Issue by SimonMolinsky** [opengeos/segment-geospatial#179]
Hi @giswqs ,

I've checked everything, and the package is outstanding! There are minor glitches that can be addressed to make using the package more accessible for newcomers:

1. I usually look into `README` to check how to install the package. Could you add a section below `Demos` or a link to the installation procedure in Readme?
2. In the installation example with conda, you use `Python=3.10`. I was wondering if it is the minimal version required, so I installed and tested the package with `Python=3.8`, and it worked fine. Is there a reason to fix the version of Python in the installation example?

Code quality is important to me, and I enjoyed how clean and concise your code is. You have provided excellent examples, and API is easy to grasp. Thank you for your work.

**Comment by giswqs** [comment]
@SimonMolinsky Thank you for your feedback. The issues have been fixed in #180

- An installation section have been added to README
- The package supports Python >=3.8, which is specificed [here](https://github.com/opengeos/segment-geospatial/blob/main/setup.py#L34). I have removed the version pin 3.10 in the installation instructions. Without the pin, conda will usually install the latest version. For now, it is 3.11. Since 3.11 has been out for a while, all samgeo package dependencies have now supported Python 3.11, so it is safe to remove the 3.10 version pin.
