### ISSUE TITLE
Input points poor performance

### ISSUE THREAD

**Issue by SFrav** [opengeos/segment-geospatial#41]
Thank you for your speedy work on this. Impressive.

I'm posting to check whether there is a known issue with the point input feature. I have tried to run the example with one point and several points and the output is very poor. I also experimented with different sam_kwargs and that didn't improve it either.

The automatic mask generator example works fine for me.

**Comment by giswqs** [comment]
Single input point should work fine. See https://samgeo.gishub.org/examples/input_prompts and https://youtu.be/WQJTMoeUx84

Multiple input points might not work well with foreground points only, i.e., no background points. This will be fixed in the next release. See #39 

If single point input does not work for you, please provide the sample image and results.

**Comment by giswqs** [comment]
Try out the new version with an interactive GUI for creating foreground and background points.

https://github.com/opengeos/segment-geospatial/assets/5016453/7e22b9c6-7849-469c-b284-5a1740e824a9
